sudo: required
services:
  - docker

before_install:
  # Tests preparation
  - ls

script:
  # Tests goes here
  - echo "Passed"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: aristaeus
  on:
    branch: master
